---
dns_intname: "eth1"
dns_nameservers:
  - DNS1=172.16.255.254
dns_search: avalon.lan

rhbase_firewall_allow_services:
  - dhcp
dhcp_global_default_lease_time: 86400
dhcp_global_max_lease_time: 86400
dhcp_global_subnet_make: 255.255.0.0
dhcp_global_domain_name: avalon.lan
dhcp_global_domain_name_servers:
      - 172.16.255.254
dhcp_global_routers: 172.16.255.254           
dhcp_subnets:
      - ip: 172.16.0.0
        netmask: 255.255.0.0
        range_begin: 172.16.128.1
        range_end: 172.16.191.254
      - ip: 172.16.0.0
        netmask: 255.255.0.0
        range_begin: 172.16.192.1
        range_end: 172.16.255.253
dhcp_hosts: 
  - name: fedora
    mac: 08:00:27:23:52:23
    ip: 172.16.155.155


    